# comments begin with #

# for convenience, define variable $(OBJS) to list of object files
OBJS= draw_shapes.o draw_chars.o 5x7-font.o uimain.o

# make has a "default rule" specifying how to build a an "object" file (.o) from a C source file (.c)
#            this rule includes $(CFLAGS) as one of cc's parameters 
CFLAGS=-g -O3 # -g for debug, -O3 for optimization

# first target is built by default.  Usually named "all"
all: asciidraw

# asciidraw (target) depends on all object files (prerequisites)
asciidraw: $(OBJS) 
	cc -o asciidraw $(CFLAGS) $(OBJS)

# all object files built from c files that include draw.h
draw_shapes.o: draw_shapes.c draw.h
	cc -c $(CFLAGS) draw_shapes.c -o draw_shapes.o

draw_chars.o: draw_chars.c draw.h
	cc -c $(CFLAGS) draw_chars.c -o draw_chars.o

5x7-font.o: 5x7-font.c draw.h
	cc -c $(CFLAGS) 5x7-font.c -o 5x7-font.o

uimain.o: uimain.c draw.h
	cc -c $(CFLAGS) uimain.c -o uimain.o
# deletes files generated by compilation
clean:
	rm -f *.o asciidraw

run:asciidraw
	./asciidraw
